name             "scpr-externalnet"
maintainer       "Eric Richardson"
maintainer_email "e@ewr.is"
license          "BSD"
description      "Configure eth1 for externally-connected hosts"
long_description ""
version          "0.1.0"

depends "network_interfaces"
depends "iptables-ng"