name             "scpr-externalnet"
maintainer       "Eric Richardson"
maintainer_email "e@ewr.is"
license          "BSD"
description      "Configure eth1 for Externally-connected Hosts"
long_description ""
version          "0.0.6"

depends "network_interfaces"
depends "iptables-ng"